#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=itrans_multivar_fc_LibriVoxSpeech
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:30:00
#SBATCH --output=slurm_output/itrans_multivar_fc_LibriVoxSpeech_%A.out


START_TIME=$(date +%s)

module purge
module load 2023
module load Anaconda3/2023.07-2

# Activate your environment
source activate sdmamba


chmod +x scripts/multivariate_forecasting/LibriVoxSpeech/S_Mamba_msg.sh
srun bash scripts/multivariate_forecasting/LibriVoxSpeech/S_Mamba_msg.sh

END_TIME=$(date +%s)
ELAPSED_TIME=$((END_TIME - START_TIME))

echo "Total execution time (seconds): ${ELAPSED_TIME}s"